-- ============================================================
-- Mente Viva · Seed CID-10 — Psiquiatria (F) e Neuro/Geriatria (G)
-- Os mais usados em consultório. Busca livre cobre o resto.
-- ============================================================

insert into cid_catalog (code, description, chapter, version) values
-- ===== F: Transtornos mentais e comportamentais =====
('F00','Demência na doença de Alzheimer','F','10'),
('F01','Demência vascular','F','10'),
('F03','Demência não especificada','F','10'),
('F05','Delirium não induzido por álcool ou drogas','F','10'),
('F06','Outros transtornos mentais por lesão cerebral','F','10'),
('F10','Transtornos mentais por uso de álcool','F','10'),
('F11','Transtornos mentais por uso de opióides','F','10'),
('F12','Transtornos mentais por uso de canabinoides','F','10'),
('F14','Transtornos mentais por uso de cocaína','F','10'),
('F17','Transtornos mentais por uso de tabaco','F','10'),
('F19','Transtornos por múltiplas drogas','F','10'),
('F20','Esquizofrenia','F','10'),
('F21','Transtorno esquizotípico','F','10'),
('F22','Transtornos delirantes persistentes','F','10'),
('F23','Transtornos psicóticos agudos e transitórios','F','10'),
('F25','Transtornos esquizoafetivos','F','10'),
('F29','Psicose não orgânica não especificada','F','10'),
('F30','Episódio maníaco','F','10'),
('F31','Transtorno afetivo bipolar','F','10'),
('F32','Episódio depressivo','F','10'),
('F33','Transtorno depressivo recorrente','F','10'),
('F34','Transtornos de humor persistentes','F','10'),
('F40','Transtornos fóbico-ansiosos','F','10'),
('F41','Outros transtornos ansiosos','F','10'),
('F41.0','Transtorno de pânico','F','10'),
('F41.1','Transtorno de ansiedade generalizada','F','10'),
('F42','Transtorno obsessivo-compulsivo','F','10'),
('F43','Reações ao estresse grave e transtornos de adaptação','F','10'),
('F43.1','Transtorno de estresse pós-traumático','F','10'),
('F44','Transtornos dissociativos','F','10'),
('F45','Transtornos somatoformes','F','10'),
('F50','Transtornos da alimentação','F','10'),
('F50.0','Anorexia nervosa','F','10'),
('F50.2','Bulimia nervosa','F','10'),
('F51','Transtornos do sono não orgânicos','F','10'),
('F60','Transtornos específicos da personalidade','F','10'),
('F70','Retardo mental leve','F','10'),
('F84','Transtornos globais do desenvolvimento','F','10'),
('F84.0','Autismo infantil','F','10'),
('F90','Transtornos hipercinéticos (TDAH)','F','10'),
('F91','Transtornos de conduta','F','10'),
('F99','Transtorno mental não especificado','F','10'),
-- ===== G: Doenças do sistema nervoso (geriatria/neuro) =====
('G20','Doença de Parkinson','G','10'),
('G21','Parkinsonismo secundário','G','10'),
('G30','Doença de Alzheimer','G','10'),
('G31','Outras degenerações do sistema nervoso','G','10'),
('G31.0','Atrofia cerebral circunscrita (demência frontotemporal)','G','10'),
('G35','Esclerose múltipla','G','10'),
('G40','Epilepsia','G','10'),
('G43','Enxaqueca','G','10'),
('G45','Acidentes isquêmicos cerebrais transitórios','G','10'),
('G47','Distúrbios do sono','G','10'),
('G47.0','Insônia','G','10'),
('G47.3','Apneia do sono','G','10'),
('G62','Polineuropatias','G','10'),
('G93','Outros transtornos do encéfalo','G','10')
on conflict (code) do update set description = excluded.description;
